[site.tool]
name='工具'
    [[site.tool.sites]]
    url='https://mrdear.cn'
    name='屈定的blog'
    desc='屈定的个人博客'

[site.blog]
name='博客收藏'
    [[site.blog.sites]]
    url='https://mrdear.cn'
    name='屈定的blog'
    desc='屈定的个人博客'
