title='屈定的Dashboard'
avatar='https://avatars0.githubusercontent.com/u/60027363?s=40&v=4'

[site.tool]
name='工具'
    [[site.tool.sites]]
    url='https://mrdear.cn'
    name='屈定的blog'
    desc='屈定的个人博客'

[site.blog]
name='博客收藏'
    [[site.blog.sites]]
    url='https://mrdear.cn'
    name='屈定的blog'
    desc='屈定的个人博客'
