[tool]
name='工具'
    [[tool.sites]]
    url='https://mrdear.cn'
    name='屈定的blog'
    desc='屈定的个人博客'

[blog]
name='博客收藏'
    [[blog.sites]]
    url='https://mrdear.cn'
    name='屈定的blog'
    desc='屈定的个人博客'
